server:
  port: 4000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: webserver
          uri: http://localhost:4001/
          predicates:
            - Path=/server/**
        - id: webclient
          uri: http://localhost:4002/
          predicates:
            - Path=/client/**

